### ISSUE TITLE
Not able to pull dependency

### ISSUE THREAD

**Issue by himekifee** [auoeke/dynamic-entry#1]
I know `bintray` is down so I used `https://auoeke.jfrog.io/ui/native/maven` but it reported 403 forbidden. I'm able to open it in the browser so I'm wondering if there is an option to allow access from gradle in Jfrog.

**Comment by auoeke** [comment]
https://auoeke.jfrog.io/artifactory/maven should work.

**Comment by himekifee** [comment]
It works, thanks.

**Comment by himekifee** [comment]
Btw do you grossfabrichackers have a universal maven repo? The GFH in the GitHub repo depends on `dynamicentry` instead of `dynamic-entry`. Your maven only provide the latter.

**Comment by auoeke** [comment]
No. Now that you mention it, I should update my fork.
